import pygame

pygame.init()
GAP = 10
MAP_SIZE = MAP_WIDTH, MAP_HEIGHT = 600, 450
UI_INPUT_HEIGHT = 50
UI_ADDRESS_HEIGHT = 20
UI_BUTTONS_WIDTH, UI_BUTTONS_HEIGHT = 200, MAP_HEIGHT
RES = WIDTH, HEIGHT = (
    MAP_WIDTH + UI_BUTTONS_WIDTH + 3 * GAP,
    MAP_HEIGHT + UI_INPUT_HEIGHT + UI_ADDRESS_HEIGHT + 4 * GAP,
)
UI_INPUT_ACTIVE_COLOR = "#4B4B58"
UI_INPUT_INACTIVE_COLOR = "#1E1E2E"
UI_INPUT_TEXT_COLOR = "#CDD6F4"
UI_BG_COLOR = "#11111B"
UI_BUTTON_HOVER_COLOR = "#24242D"
UI_TEXT_ACTIVE_COLOR = "#C5C5C8"
UI_TEXT_INACTIVE_COLOR = "#A1A1A5"
